namespace MyApp.Api.DTOs;

// ── Auth ─────────────────────────────────────────────────────────────────────

public record RegisterDto(
    string FullName,
    string Email,
    string Password,
    string Role = "User"
);

public record LoginDto(
    string Email,
    string Password
);

public record AuthResponseDto(
    UserResponseDto User,
    string Token          // JWT — generated by your auth layer / controller
);

// ── Admin user management ────────────────────────────────────────────────────

public record UserCreateDto(string FullName, string Email, string Password, string Role = "User");

public record UserUpdateDto(string FullName, string Email);

public record ChangePasswordDto(
    string CurrentPassword,
    string NewPassword
);

public record UserResponseDto(
    Guid Id,
    string FullName,
    string Email,
    string Role,
    DateTime CreatedAt,
    DateTime UpdatedAt
);